#!/bin/sh
dir=$1
if [ ! $dir ]; then
    dir='.'
fi
ls -l "$dir" | 
grep "\->" |
awk '
    {
        colorBlue = 1;
        colorGreen = 0;
        for(i = 9; i <= NF; i++){
            if($i == "->"){
                colorBlue = 0;
                colorGreen = 1;
            }
            if(colorGreen == 1 && $i != "->"){
                $i = "\033[32;1m" $i "\033[0m";
            }
            if(colorBlue == 1){
                $i = "\033[36;1m" $i "\033[0m";
            }
            printf $i " ";
        }
        printf "\n";
    }
' 
