#!/bin/sh
input=$input

[ -z $CONFIG_FILE ] && CONFIG_FILE="$XDG_CONFIG_HOME/current_wallpaper"
[ -z $DEFAULT_WPP_DIR ] && DEFAULT_WPP_DIR="$HOME/wallpapers"

[ -z "$input" ] && input="$DEFAULT_WPP_DIR"

# If arg 1 is a file, write its path to the configuration file
[ -f "$input" ] && {
    if [ "$(echo $input | grep -E "(jpg,jpeg,png,bmp)")" ]; then
        echo "$input" > "$CONFIG_FILE"
        notify-send -i $(cat "$CONFIG_FILE") "Wallpaper changed"
    else 
        notify-send "Wallpaper not changed."
    fi
}

# If arg 1 is a directory, choose a random image from it
if [ -d "$input" ]; then
    nextWallpaper=$(echo "$({
    find "$input" -maxdepth 3 -regex "$input/.*\.\(jpg\|jpeg\|png\|bmp\)$" -type f 2>/dev/null  ||
        # If find fails, do not change the wallpaper
            echo "__FAIL__"
        })" | grep -vx "$(cat $CONFIG_FILE)" | shuf -n 1)
    [ "$nextWallpaper" = "__FAIL__" ] && 
        notify-send "Wallpaper not changed."
    [ "$nextWallpaper" != "$(cat $CONFIG_FILE)" ] && 
        notify-send -i "$nextWallpaper" "Random wallpaper chosen." &&
        echo "$nextWallpaper" > "$CONFIG_FILE"
fi

hsetroot -solid 'black' -fill "$(cat "$CONFIG_FILE")" >/dev/null 2>&1 ||
    notify-send -u critical "Error while setting wallpaper"; exit 1
